stages:
  topic_model:
    cmd: python topic_model.py
    deps:
      - topic_model.py
      - data/tweets.csv
    outs:
      - outputs/project_BERTopic
  multiclass_state:
    cmd: python multiclass_state.py 
    deps:
      - multiclass_state.py
      - data/tweets.csv
      - data/elected_officials.csv
    outs:
      - outputs/mc_state_pipe.pkl
    params:
      - preprocessing.max_min_docs
      - preprocessing.n_grams
    metrics:
      - metrics/mc_state_metrics.json:
          cache: false
  multiclass_office:
    cmd: python multiclass_office.py
    deps:
      - multiclass_office.py
      - data/tweets.csv
      - data/elected_officials.csv
    outs:
      - outputs/mc_office_pipe.pkl
    params:
      - preprocessing.max_min_docs
      - preprocessing.n_grams
    metrics:
      - metrics/mc_office_metrics.json:
         cache: false
  #stage_3:
  #  cmd: python rank_regression.py
  #  deps:
  #    - rank_regression.py
  #    - ../../../data/mtg.feather
  #  outs:
  #    - regression_GridSearch.pkl