stages:
  topic_model:
    cmd: python topic_model.py
    deps:
      - topic_model.py
      - data/tweets.csv
    outs:
      - outputs/project_BERTopic
  multiclass_state:
    cmd: python multiclass_state.py 
    deps:
      - multiclass_state.py
      - data/tweets.csv
      - data/elected_officials.csv
    outs:
      - outputs/mc_state_pipe.pkl
    params:
      - preprocessing.max_min_docs
      - preprocessing.n_grams
    metrics:
      - metrics/mc_state_metrics.json:
          cache: false
  multiclass_office:
    cmd: python multiclass_office.py
    deps:
      - multiclass_office.py
      - data/tweets.csv
      - data/elected_officials.csv
    outs:
      - outputs/mc_office_pipe.pkl
    params:
      - preprocessing.max_min_docs
      - preprocessing.n_grams
    metrics:
      - metrics/mc_office_metrics.json:
         cache: false
  twoclass_party:
    cmd: python twoclass_party.py
    deps:
      - twoclass_party.py
      - data/tweets.csv
      - data/elected_officials.csv
    outs:
      - outputs/bc_party_pipe.pkl
    params:
      - preprocessing.max_min_docs
      - preprocessing.n_grams
    metrics:
      - metrics/bc_party_metrics.json:
         cache: false